### ISSUE TITLE
Error page when adding more functionality to the user

### ISSUE THREAD

**Issue by saiaashraya** [UCDS/health4all_today#26]
![Screen Shot 2022-01-17 at 9 31 50 AM](https://user-images.githubusercontent.com/97846202/149942626-70aceded-1c49-44f6-92dd-c3659ed563c4.png)
![Screen Shot 2022-01-17 at 9 00 58 AM](https://user-images.githubusercontent.com/97846202/149942637-fccc648d-a7bc-44d5-ae8a-cf8db8f69eca.png)

**Comment by Manish-Kumar-Sadhu** [comment]
@saiaashraya  please close this issue here and open it in **health4all_v3** repo, as this issue is not related to **health4all_today**
